# Generated by Django 2.2.6 on 2019-10-16 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(editable=False, help_text='Email Address', max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text='First Name', max_length=128)),
                ('last_name', models.CharField(help_text='Surname', max_length=128)),
                ('middle_name', models.CharField(blank=True, help_text='Middle Name', max_length=128)),
                ('nationality', django_countries.fields.CountryField(help_text='Country of Origin', max_length=2)),
                ('primary_phone_number', phone_field.models.PhoneField(help_text='Primary Phone Number', max_length=31)),
                ('secondary_phone_number', phone_field.models.PhoneField(blank=True, help_text='Secondary Phone Number', max_length=31)),
                ('date_of_birth', models.DateTimeField(help_text='Date Of Birth')),
                ('date_joined', models.DateTimeField(help_text='Date of Registration')),
                ('passport_number', models.CharField(blank=True, help_text='Passport Registration Number', max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='User Sex', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idenfition_number', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.user',),
        ),
    ]
