# Generated by Django 2.2.6 on 2019-10-27 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='date_propsed',
        ),
        migrations.AddField(
            model_name='gig',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gig',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Parent'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/avatars//default.jpg', upload_to='static/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BinaryField(blank=True, choices=[(0, 'Not Specified'), (0, 'Male'), (1, 'Female')], default=None, help_text='User Sexual Orenitation', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='Kenyan Idenifition Number', max_length=8, null=True),
        ),
    ]
