# Generated by Django 2.2.6 on 2019-10-16 19:58

from django.db import migrations, models
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_certificate_number',
            field=models.CharField(default='', help_text='Birth Certificate Number', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, help_text='Family Name', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(default='', help_text='Primary Phone Number', max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='idenfition_number',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(default='', help_text='Passport Registration Number', max_length=16, unique=True),
        ),
    ]
