# Generated by Django 2.2.6 on 2019-10-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191016_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name',
            field=models.CharField(help_text='Family Name', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(help_text='Middle Name', max_length=128),
        ),
    ]
