# Generated by Django 2.2.6 on 2019-10-16 20:13

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191016_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_certificate_number',
            field=models.CharField(help_text='Birth Certificate Number', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(help_text='Passport Registration Number', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Primary Phone Number', max_length=31),
        ),
    ]
