# Generated by Django 2.2.6 on 2019-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191016_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='Required. The Day you were Born.Address same as on your Birth Certificate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Required. Your First Name, same as on your Birth Certificate', max_length=128),
        ),
    ]
